.TH SHELL 1 "April 2024" "Version 1.0" "Shell Program Manual"

.SH NAME
shell \- A simple shell program

.SH SYNOPSIS
simple shell

.SH DESCRIPTION
The shell program provides a basic command-line interface for executing commands. It reads commands from the user, executes them, and displays the results.

.SH OPTIONS
There are no command-line options for the shell program.

.SH COMMANDS
The shell program supports the following built-in commands:
ls
ls -l
pwd
cat
exit

.IP "\fBexit\fR"
Exit the shell program.

.SH EXAMPLES
Run the shell program:
.BR shell

.SH SEE ALSO
.BR sh (1),
.BR bash (1),
.BR readline (3).

.SH BUGS
No known bugs till day.

.SH AUTHORS
Anibal Fuentes Rodriguez.
Abdiel J. Rodriguez Gonzalez.

.SH CONTACT
Anibal Fuentes Rodriguez.
Email: 9045@holbertonstudents.com
GitHub:anibalfuentesrod

Abdiel J. Rodriguez Gonzalez.
Email: 9048@holbertonstudents.com
GitHub: abdieljrg
